# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: github.repository == 'jnhk123/momjobgo-project'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
      # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.USERNAME }}
        # Remote port
        REMOTE_PORT: ${{ secrets.PORT }}
        #SOURCE : build/libs
        # Target directory
        TARGET: /home/momjobgo-vue/deploy_dir
